import os
from dotenv import load_dotenv
from google.adk import Agent
from google.adk.agents import SequentialAgent
from google.adk.tools import AgentTool

from agents.topic_agent import topic_agent
from agents.script_agent import script_agent
from agents.narrator_agent import narrator_agent
from agents.slide_agent import slide_agent
from agents.video_compiler_agent import video_compiler_agent
from agents.exercise_agent import exercise_agent
from agents.answer_agent import answer_agent
from tools.state_tool import save_topic, load_topic, save_exercises, load_exercises, save_script, load_script

load_dotenv()

INSTRUCTIONS = """

You are the Orchestrator.

RULE 1 — Exercise Mode
-----------------------
If the user message contains:
"exercise", "practice", "questions", "quiz", "test"

1. First call load_script.
2. If load_script returns an empty or null script, respond with:
   "Please generate a video first before asking for exercises."
3. Call ExerciseAgent with the script_text returned from load_script.
4. When ExerciseAgent returns the exercise content, **IMPERATIVELY CALL** save_exercises with the *entire output* of ExerciseAgent.
   (e.g., save_exercises(exercises=<output of ExerciseAgent>))
5. **FINALLY**, return ONLY the content generated by the ExerciseAgent to the user.
6. Do NOT run the video pipeline in this mode.


RULE 2 — Full Video Pipeline
----------------------------

Your task is:

1. Receive the user's input text.
2. Call the 'topic_agent' to generate a short topic name (max 2 words) from the input.
    - After receiving the topic_name, IMMEDIATELY call save_topic(topic_name=...).
3. Call the 'script_agent' to generate a complete educational script based on the user's input.
    - After receiving the script content, IMMEDIATELY call save_script(script_text=...).
4. Now, call the 'media_pipeline' agent with ONE argument named 'request'.
   The value of 'request' must be a JSON string containing the following keys:
      - "topic": the topic name from step 2
      - "script": the script content from step 3
   Example of the argument structure: 
   request='{"topic": "Basic Algebra", "script": "Slide 1 Title. This is the content..."}'

5. When the 'media_pipeline' returns the MP4 file path,
   your FINAL MESSAGE must contain ONLY that file path.
   Absolutely no extra text, no quotes, no JSON, no explanation.
   Example of final output:
   /app/data/videos/quantum_physics.mp4


RULE 3 — Exercise Answers
-------------------------
If the user message contains any of the following words (case-insensitive):
"answer", "answers", "solution", "solutions", "answer key", "check", "show answers":

1. Call load_exercises to retrieve the stored practice questions.
2. If no stored exercises exist, respond:
   "No exercises are saved. Please request exercises first."

3. Otherwise call AnswerAgent with ONE argument named "request".
   The value MUST be a JSON string containing the stored exercises.

   Example:
   AnswerAgent(request="{\"exercises\":\"<stored_text>\"}")

4. Return the combined result:
   Exercises + Answers.

"""

media_pipeline = SequentialAgent(
    sub_agents=[
        slide_agent,
        narrator_agent,
        video_compiler_agent,
    ],
    name="media_pipeline"
)

orchestrator_agent = Agent(
    model=os.getenv("MODEL_TEXT"),
    name="orchestrator",
    description="Generates the educational video by orchestrating multiple specialized agents.",
    instruction=INSTRUCTIONS,
    tools=[
        AgentTool(agent=topic_agent),
        AgentTool(agent=script_agent),
        AgentTool(agent=media_pipeline),
        AgentTool(agent=exercise_agent),
        AgentTool(agent=answer_agent),
        save_topic,
        load_topic,
        save_script,
        load_script,
        save_exercises,
        load_exercises,
    ],
)